Improved error message

diff --git a/snap/hooks/post-refresh b/snap/hooks/post-refresh
--- a/snap/hooks/post-refresh
+++ b/snap/hooks/post-refresh
@@ -40,6 +40,8 @@ if [ ! -d "$datadir/$ver/main" ]; then
 fi
 
 if [ "$ver" != "${SNAP_VERSION%%.*}" ]; then
-    echo "ERROR: Data is from PostgreSQL $ver but this revision provides ${SNAP_VERSION%%.*}. Stay on $ver/* or migrate with pg_dump/pg_restore. Refresh aborted, rolling back." >&2
+    echo "ERROR: Data is from PostgreSQL $ver but this revision provides ${SNAP_VERSION%%.*}. \
+    In order to migrate between major versions, use pg_dump/pg_restore or check for new snap revision \
+    which may support in-place upgrades. Refresh aborted, rolling back." >&2
     exit 1
 fi
